[package]
name = "dataEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"   
execute = "0.2.12"
fastrand = "1.9.0"
mysql = "*"   
rand = "0.8.4"
